import { OpenAPIV3 } from "openapi-types";

export const saleSchemas: OpenAPIV3.ComponentsObject["schemas"] = {
  Sale: {
    type: "object",
    required: [
      "id",
      "invoice_number",
      "cashier_id",
      "customer_id",
      "subtotal",
      "discount",
      "total",
      "status",
      "created_at",
      "updated_at",
      "items",
      "payments",
    ],
    properties: {
      id: {
        type: "string",
        format: "uuid",
        description: "Sale UUID.",
        example: "69d0c9fa-461b-4e87-97ce-f89ee8877316",
      },

      invoice_number: {
        type: "string",
        description: "Unique sale invoice number generated by the server.",
        example: "INV260927000001",
      },

      cashier_id: {
        type: "string",
        format: "uuid",
        description: "UUID of the cashier who created the sale.",
        example: "550e8400-e29b-41d4-a716-446655440000",
      },

      customer_id: {
        type: "string",
        format: "uuid",
        nullable: true,
        description:
          "Customer UUID. Null when the sale is not associated with a customer.",
        example: null,
      },

      subtotal: {
        type: "number",
        format: "double",
        minimum: 0,
        description: "Total amount before discount.",
        example: 100000,
      },

      discount: {
        type: "number",
        format: "double",
        minimum: 0,
        description: "Discount applied to the sale.",
        example: 5000,
      },

      total: {
        type: "number",
        format: "double",
        minimum: 0,
        description: "Final sale amount after discount.",
        example: 95000,
      },

      status: {
        type: "string",
        enum: ["completed", "void"],
        description: "Sale status.",
        example: "completed",
      },

      created_at: {
        type: "string",
        format: "date-time",
        description: "Sale creation timestamp.",
        example: "2026-09-27T03:30:00Z",
      },

      updated_at: {
        type: "string",
        format: "date-time",
        nullable: true,
        description: "Sale last update timestamp.",
        example: "2026-09-27T03:30:00Z",
      },

      items: {
        type: "array",
        description: "Products included in the sale.",
        items: {
          $ref: "#/components/schemas/SaleItem",
        },
      },

      payments: {
        type: "array",
        description: "Payments associated with the sale.",
        items: {
          $ref: "#/components/schemas/Payment",
        },
      },
    },
  },

  SaleItem: {
    type: "object",
    required: [
      "id",
      "sale_id",
      "product_id",
      "quantity",
      "unit_price",
      "subtotal",
      "created_at",
    ],
    properties: {
      id: {
        type: "string",
        format: "uuid",
        description: "Sale item UUID.",
        example: "c7f1b9a2-9e4d-4d2e-8b2d-1b7f4c9e1234",
      },

      sale_id: {
        type: "string",
        format: "uuid",
        description: "Sale UUID.",
        example: "69d0c9fa-461b-4e87-97ce-f89ee8877316",
      },

      product_id: {
        type: "string",
        format: "uuid",
        description: "Product UUID.",
        example: "5b8f3c21-7a6e-4d91-b2f8-8c3e1a456789",
      },

      quantity: {
        type: "integer",
        minimum: 1,
        description: "Quantity of the product sold.",
        example: 2,
      },

      unit_price: {
        type: "number",
        format: "double",
        minimum: 0,
        description: "Product selling price at the time of sale.",
        example: 3500,
      },

      subtotal: {
        type: "number",
        format: "double",
        minimum: 0,
        description: "Subtotal for this sale item.",
        example: 7000,
      },

      created_at: {
        type: "string",
        format: "date-time",
        description: "Sale item creation timestamp.",
        example: "2026-09-27T03:30:00Z",
      },
    },
  },

  Payment: {
    type: "object",
    required: ["id", "sale_id", "method", "amount", "created_at"],
    properties: {
      id: {
        type: "string",
        format: "uuid",
        description: "Payment UUID.",
        example: "a1b2c3d4-e5f6-4789-abcd-123456789012",
      },

      sale_id: {
        type: "string",
        format: "uuid",
        description: "Sale UUID.",
        example: "69d0c9fa-461b-4e87-97ce-f89ee8877316",
      },

      method: {
        type: "string",
        enum: ["cash", "qris", "card", "transfer"],
        description: "Payment method.",
        example: "cash",
      },

      amount: {
        type: "number",
        format: "double",
        exclusiveMinimum: true,
        description: "Payment amount.",
        example: 100000,
      },

      created_at: {
        type: "string",
        format: "date-time",
        description: "Payment creation timestamp.",
        example: "2026-09-27T03:30:00Z",
      },
    },
  },

  CreateSaleItemRequest: {
    type: "object",
    required: ["product_id", "quantity"],
    properties: {
      product_id: {
        type: "string",
        format: "uuid",
        description: "Product UUID.",
        example: "5b8f3c21-7a6e-4d91-b2f8-8c3e1a456789",
      },

      quantity: {
        type: "integer",
        minimum: 1,
        description: "Quantity of the product to sell.",
        example: 2,
      },
    },
  },

  CreateSalePaymentRequest: {
    type: "object",
    required: ["method", "amount"],
    properties: {
      method: {
        type: "string",
        enum: ["cash", "qris", "card", "transfer"],
        description: "Payment method.",
        example: "cash",
      },

      amount: {
        type: "number",
        format: "double",
        exclusiveMinimum: true,
        description: "Payment amount.",
        example: 100000,
      },
    },
  },

  CreateSaleRequest: {
    type: "object",
    required: ["items", "payments"],
    properties: {
      customer_id: {
        type: "string",
        format: "uuid",
        description: "Customer UUID.",
        example: "550e8400-e29b-41d4-a716-446655440000",
      },

      discount: {
        type: "number",
        format: "double",
        minimum: 0,
        default: 0,
        description: "Discount applied to the sale.",
        example: 5000,
      },

      items: {
        type: "array",
        minItems: 1,
        description: "Products included in the sale.",
        items: {
          $ref: "#/components/schemas/CreateSaleItemRequest",
        },
      },

      payments: {
        type: "array",
        minItems: 1,
        description: "Payments made for the sale.",
        items: {
          $ref: "#/components/schemas/CreateSalePaymentRequest",
        },
      },
    },
  },
};
